Wi-Fi Static IP
StarfishCo/cordova-hotspot-plugin pull request #23
Opened 2021-07-07 18:44 UTC by marvinraven

Adds a number of methods that allow user to configure a static IP on the device for Wi-Fi connection.

2021-07-13 14:37 UTC, JacobStarfish requested changes
Couple minor Java styling things

2021-07-13 14:37 UTC, JacobStarfish commented on src/android/de/martinreinhardt/cordova/plugins/hotspot/HotSpotPlugin.java
> +      Log.e(LOG_TAG, "Set IP config failed", e);
I think you need to do `e.getMessage()` to get the actual error message for logging

2021-07-13 14:37 UTC, JacobStarfish commented on src/android/de/martinreinhardt/cordova/plugins/hotspot/HotSpotPlugin.java
> +    // Apply new config
can this be moved within function's try/catch to prevent any other JSONExceptions from causing a crash?

2021-07-15 14:19 UTC, marvinraven commented on src/android/de/martinreinhardt/cordova/plugins/hotspot/HotSpotPlugin.java
> +      Log.e(LOG_TAG, "Set IP config failed", e);
Done

2021-07-15 14:19 UTC, marvinraven commented on src/android/de/martinreinhardt/cordova/plugins/hotspot/HotSpotPlugin.java
> +    // Apply new config
Done

2021-07-29 22:19 UTC, JacobStarfish approved these changes
Hard one to review... mostly 🤞 it works

2021-07-30 18:01 UTC, denisbrex approved these changes

2021-07-30 20:28 UTC, merged