Hidden ssid
StarfishCo/cordova-hotspot-plugin pull request #4
Opened 2019-06-12 14:55 UTC by JacobStarfish

For #582

- Makes changes to plugin needed to connect to networks with a hidden SSID

2019-06-13 12:33 UTC, goodevilgenius approved these changes

2019-06-13 15:48 UTC, mehtaamish89 requested changes

2019-06-13 15:48 UTC, mehtaamish89 commented on src/android/de/martinreinhardt/cordova/plugins/hotspot/HotSpotPlugin.java
> +    public boolean hasPermissions() {
Looks like the indentation for this is increased from 2 to 4, can you revert it back to 2 spaces so it matches with other projects.
- [ ] Done
- [ ] Approved

2019-06-17 19:29 UTC, mehtaamish89 approved these changes

2019-06-17 19:32 UTC, merged